language: d

d:
  - dmd-2.067.0
  - dmd-2.066.1
  - gdc-4.9.0
  - ldc-0.14.0

addons:
  postgresql: 9.4

services: postgresql

before_script:
  - psql -c 'create database "dpq2-test"' -U postgres

script:
  - dub test
  - cd integration_tests && dub -- --conninfo "dbname=postgres" && cd -
  - dub build --build=release
  - cd example && dub && cd -
