language: d

d:
  - dmd
  - gdc
  - ldc

addons:
  postgresql: 9.4

services: postgresql

before_install:
  - git clone --depth=1 --recursive https://github.com/Hackerpilot/Dscanner.git ~/Dscanner

install:
  - if [ ${DC} = "dmd" ]; then make -C ~/Dscanner; fi

before_script:
  - psql -c 'create database "dpq2-test"' -U postgres

script:
  - dub build
  - dub test
  - cd integration_tests && dub -- --conninfo "dbname=postgres" && cd -
  - if [[ -x "~/Dscanner/bin/dscanner" ]]; then ~/Dscanner/bin/dscanner -s; fi
  - if [[ -x "~/Dscanner/bin/dscanner" ]]; then ~/Dscanner/bin/dscanner -S; fi
  - dub build --build=release
  - cd example && dub && cd -
  - cd example && dub --build=release && cd -
