language: d

d:
  - dmd
  - gdc
  - ldc

addons:
  postgresql: 9.4

services: postgresql

before_install:
  - git clone --depth=1 --recursive https://github.com/Hackerpilot/Dscanner.git ~/Dscanner
  - dub fetch doveralls

install:
  - if [ ${DC} = "dmd" ]; then make -C ~/Dscanner; fi

before_script:
  - psql -c 'create database "dpq2-test"' -U postgres

script:
  - dub build --build=unittest-cov
  - cd integration_tests && dub run --build=unittest-cov -- --conninfo "dbname=postgres" && cd -
  - if [ ${DC} = "dmd" ]; then ~/Dscanner/bin/dscanner -s; fi
  - if [ ${DC} = "dmd" ]; then ~/Dscanner/bin/dscanner -S; fi
  - dub build --build=release
  - cd example && dub --build=unittest-cov && cd -
  - cd example && dub --build=release && cd -

after_success:
  - dub run doveralls
