language: d

d:
  - dmd
  - gdc
  - ldc

addons:
  postgresql: 9.4

services: postgresql

before_install:
  - git clone --depth=1 --recursive https://github.com/Hackerpilot/Dscanner.git ~/Dscanner
  - dub fetch doveralls

install:
  - if [ ${DC} = "dmd" ]; then make -C ~/Dscanner; fi

before_script:
  - psql -c 'create database "dpq2-test"' -U postgres

script:
  - dub add-local .
  - dub add-local integration_tests
  - dub add-local example

  - dub run dpq2-integration_tests --build=unittest-cov

  - if [ ${DC} = "dmd" ]; then ~/Dscanner/bin/dscanner -s; fi
  - if [ ${DC} = "dmd" ]; then ~/Dscanner/bin/dscanner -S; fi

  - dub build dpq2 --build=release
  - dub run example --build=release

after_success:
  - dub run doveralls
